/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param name Name of the metric.
 * @param value Value of the metric.
 * @param timestamp Unix timestamp of when the metric was recorded.
 */
data class Apiv1applicationsappIdmetricsMetrics (

    /* Name of the metric. */
    val name: kotlin.String? = null,
    /* Value of the metric. */
    val value: java.math.BigDecimal? = null,
    /* Unix timestamp of when the metric was recorded. */
    val timestamp: kotlin.Long? = null
) {
}