/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param date Date of the metric.
 * @param count Count of the metric.
 * @param p99 99th percentile of the metric.
 * @param p95 95th percentile of the metric.
 * @param p50 50th percentile of the metric.
 * @param avg Average value of the metric.
 */
data class InlineResponse2003 (

    /* Date of the metric. */
    val date: java.time.LocalDateTime? = null,
    /* Count of the metric. */
    val count: kotlin.Int? = null,
    /* 99th percentile of the metric. */
    val p99: java.math.BigDecimal? = null,
    /* 95th percentile of the metric. */
    val p95: java.math.BigDecimal? = null,
    /* 50th percentile of the metric. */
    val p50: java.math.BigDecimal? = null,
    /* Average value of the metric. */
    val avg: java.math.BigDecimal? = null
) {
}