/*
 * Your Application API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type InlineResponse2003 struct {
	// Date of the metric.
	Date time.Time `json:"date,omitempty"`
	// Count of the metric.
	Count int32 `json:"count,omitempty"`
	// 99th percentile of the metric.
	P99 float64 `json:"p99,omitempty"`
	// 95th percentile of the metric.
	P95 float64 `json:"p95,omitempty"`
	// 50th percentile of the metric.
	P50 float64 `json:"p50,omitempty"`
	// Average value of the metric.
	Avg float64 `json:"avg,omitempty"`
}
