/*
 * Your Application API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse200 struct {
	Records []interface{} `json:"records,omitempty"`
	Meta *interface{} `json:"meta,omitempty"`
}
