//
// Apiv1applicationsappIdmetricsMetrics.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Apiv1applicationsappIdmetricsMetrics: Codable {

    /** Name of the metric. */
    public var name: String?
    /** Value of the metric. */
    public var value: Decimal?
    /** Unix timestamp of when the metric was recorded. */
    public var timestamp: Int64?

    public init(name: String? = nil, value: Decimal? = nil, timestamp: Int64? = nil) {
        self.name = name
        self.value = value
        self.timestamp = timestamp
    }


}
