//
// Apiv1applicationsApplication.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Apiv1applicationsApplication: Codable {

    /** Name of the application. */
    public var name: String?

    public init(name: String? = nil) {
        self.name = name
    }


}
