//
// AppIdMetricsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct AppIdMetricsBody: Codable {

    public var metrics: [Apiv1applicationsappIdmetricsMetrics]?

    public init(metrics: [Apiv1applicationsappIdmetricsMetrics]? = nil) {
        self.metrics = metrics
    }


}
