//
// InlineResponse2003.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse2003: Codable {

    /** Date of the metric. */
    public var date: Date?
    /** Count of the metric. */
    public var count: Int?
    /** 99th percentile of the metric. */
    public var p99: Decimal?
    /** 95th percentile of the metric. */
    public var p95: Decimal?
    /** 50th percentile of the metric. */
    public var p50: Decimal?
    /** Average value of the metric. */
    public var avg: Decimal?

    public init(date: Date? = nil, count: Int? = nil, p99: Decimal? = nil, p95: Decimal? = nil, p50: Decimal? = nil, avg: Decimal? = nil) {
        self.date = date
        self.count = count
        self.p99 = p99
        self.p95 = p95
        self.p50 = p50
        self.avg = avg
    }


}
