//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct InlineResponse200: Codable {

    public var records: [Any]?
    public var meta: Any?

    public init(records: [Any]? = nil, meta: Any? = nil) {
        self.records = records
        self.meta = meta
    }


}
