//
// V1ApplicationsBody.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct V1ApplicationsBody: Codable {

    public var application: Apiv1applicationsApplication?

    public init(application: Apiv1applicationsApplication? = nil) {
        self.application = application
    }


}
