/* tslint:disable */
/* eslint-disable */
/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Apiv1applicationsApplication
 */
export interface Apiv1applicationsApplication {

    /**
     * Name of the application.
     *
     * @type {string}
     * @memberof Apiv1applicationsApplication
     */
    name?: string;
}
