/* tslint:disable */
/* eslint-disable */
/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Apiv1applicationsappIdmetricsMetrics
 */
export interface Apiv1applicationsappIdmetricsMetrics {

    /**
     * Name of the metric.
     *
     * @type {string}
     * @memberof Apiv1applicationsappIdmetricsMetrics
     */
    name?: string;

    /**
     * Value of the metric.
     *
     * @type {number}
     * @memberof Apiv1applicationsappIdmetricsMetrics
     */
    value?: number;

    /**
     * Unix timestamp of when the metric was recorded.
     *
     * @type {number}
     * @memberof Apiv1applicationsappIdmetricsMetrics
     */
    timestamp?: number;
}
