/* tslint:disable */
/* eslint-disable */
/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Apiv1applicationsappIdmetricsMetrics } from './apiv1applicationsapp-idmetrics-metrics';
 /**
 * 
 *
 * @export
 * @interface AppIdMetricsBody
 */
export interface AppIdMetricsBody {

    /**
     * @type {Array<Apiv1applicationsappIdmetricsMetrics>}
     * @memberof AppIdMetricsBody
     */
    metrics?: Array<Apiv1applicationsappIdmetricsMetrics>;
}
