/* tslint:disable */
/* eslint-disable */
/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {

    /**
     * Date of the metric.
     *
     * @type {Date}
     * @memberof InlineResponse2003
     * @example 2024-05-06T00:00Z
     */
    date?: Date;

    /**
     * Count of the metric.
     *
     * @type {number}
     * @memberof InlineResponse2003
     * @example 3
     */
    count?: number;

    /**
     * 99th percentile of the metric.
     *
     * @type {number}
     * @memberof InlineResponse2003
     * @example 30
     */
    p99?: number;

    /**
     * 95th percentile of the metric.
     *
     * @type {number}
     * @memberof InlineResponse2003
     * @example 30
     */
    p95?: number;

    /**
     * 50th percentile of the metric.
     *
     * @type {number}
     * @memberof InlineResponse2003
     * @example 5
     */
    p50?: number;

    /**
     * Average value of the metric.
     *
     * @type {number}
     * @memberof InlineResponse2003
     * @example 12.666666666666666
     */
    avg?: number;
}
