/* tslint:disable */
/* eslint-disable */
/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {

    /**
     * @type {Array<any>}
     * @memberof InlineResponse200
     */
    records?: Array<any>;

    /**
     * @type {any}
     * @memberof InlineResponse200
     */
    meta?: any;
}
