/* tslint:disable */
/* eslint-disable */
/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse201
 */
export interface InlineResponse201 {

    /**
     * ID of the created application.
     *
     * @type {string}
     * @memberof InlineResponse201
     */
    id?: string;

    /**
     * Name of the created application.
     *
     * @type {string}
     * @memberof InlineResponse201
     */
    name?: string;

    /**
     * Timestamp when the application was created.
     *
     * @type {Date}
     * @memberof InlineResponse201
     */
    createdAt?: Date;

    /**
     * Timestamp when the application was last updated.
     *
     * @type {Date}
     * @memberof InlineResponse201
     */
    updatedAt?: Date;
}
