/* tslint:disable */
/* eslint-disable */
/**
 * Your Application API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Apiv1applicationsApplication } from './apiv1applications-application';
 /**
 * 
 *
 * @export
 * @interface V1ApplicationsBody
 */
export interface V1ApplicationsBody {

    /**
     * @type {Apiv1applicationsApplication}
     * @memberof V1ApplicationsBody
     */
    application?: Apiv1applicationsApplication;
}
